//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novell.Directory.LDAP.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResultCodeMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResultCodeMessages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novell.Directory.LDAP.Properties.ResultCodeMessages", typeof(ResultCodeMessages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Success.
        /// </summary>
        public static string _0 {
            get {
                return ResourceManager.GetString("0", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Operations Error.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Referral.
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Administrative Limit Exceeded.
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to TLS not supported.
        /// </summary>
        public static string _112 {
            get {
                return ResourceManager.GetString("112", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SSL handshake failed.
        /// </summary>
        public static string _113 {
            get {
                return ResourceManager.GetString("113", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SSL Provider not found.
        /// </summary>
        public static string _114 {
            get {
                return ResourceManager.GetString("114", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unavailable Critical Extension.
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Confidentiality Required.
        /// </summary>
        public static string _13 {
            get {
                return ResourceManager.GetString("13", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SASL Bind In Progress.
        /// </summary>
        public static string _14 {
            get {
                return ResourceManager.GetString("14", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No Such Attribute.
        /// </summary>
        public static string _16 {
            get {
                return ResourceManager.GetString("16", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Undefined Attribute Type.
        /// </summary>
        public static string _17 {
            get {
                return ResourceManager.GetString("17", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Inappropriate Matching.
        /// </summary>
        public static string _18 {
            get {
                return ResourceManager.GetString("18", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Constraint Violation.
        /// </summary>
        public static string _19 {
            get {
                return ResourceManager.GetString("19", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Protocol Error.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Attribute Or Value Exists.
        /// </summary>
        public static string _20 {
            get {
                return ResourceManager.GetString("20", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Attribute Syntax.
        /// </summary>
        public static string _21 {
            get {
                return ResourceManager.GetString("21", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Timelimit Exceeded.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No Such Object.
        /// </summary>
        public static string _32 {
            get {
                return ResourceManager.GetString("32", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Alias Problem.
        /// </summary>
        public static string _33 {
            get {
                return ResourceManager.GetString("33", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid DN Syntax.
        /// </summary>
        public static string _34 {
            get {
                return ResourceManager.GetString("34", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Is Leaf.
        /// </summary>
        public static string _35 {
            get {
                return ResourceManager.GetString("35", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Alias Dereferencing Problem.
        /// </summary>
        public static string _36 {
            get {
                return ResourceManager.GetString("36", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sizelimit Exceeded.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Inappropriate Authentication.
        /// </summary>
        public static string _48 {
            get {
                return ResourceManager.GetString("48", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        public static string _49 {
            get {
                return ResourceManager.GetString("49", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Compare False.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Insufficient Access Rights.
        /// </summary>
        public static string _50 {
            get {
                return ResourceManager.GetString("50", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Busy.
        /// </summary>
        public static string _51 {
            get {
                return ResourceManager.GetString("51", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string _52 {
            get {
                return ResourceManager.GetString("52", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unwilling To Perform.
        /// </summary>
        public static string _53 {
            get {
                return ResourceManager.GetString("53", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Loop Detect.
        /// </summary>
        public static string _54 {
            get {
                return ResourceManager.GetString("54", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Compare True.
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Naming Violation.
        /// </summary>
        public static string _64 {
            get {
                return ResourceManager.GetString("64", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Object Class Violation.
        /// </summary>
        public static string _65 {
            get {
                return ResourceManager.GetString("65", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Not Allowed On Non-leaf.
        /// </summary>
        public static string _66 {
            get {
                return ResourceManager.GetString("66", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Not Allowed On RDN.
        /// </summary>
        public static string _67 {
            get {
                return ResourceManager.GetString("67", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Entry Already Exists.
        /// </summary>
        public static string _68 {
            get {
                return ResourceManager.GetString("68", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Object Class Modifications Prohibited.
        /// </summary>
        public static string _69 {
            get {
                return ResourceManager.GetString("69", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Authentication Method Not Supported.
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Affects Multiple DSAs.
        /// </summary>
        public static string _71 {
            get {
                return ResourceManager.GetString("71", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Strong Authentication Required.
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Other.
        /// </summary>
        public static string _80 {
            get {
                return ResourceManager.GetString("80", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Server Down.
        /// </summary>
        public static string _81 {
            get {
                return ResourceManager.GetString("81", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Local Error.
        /// </summary>
        public static string _82 {
            get {
                return ResourceManager.GetString("82", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Encoding Error.
        /// </summary>
        public static string _83 {
            get {
                return ResourceManager.GetString("83", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Decoding Error.
        /// </summary>
        public static string _84 {
            get {
                return ResourceManager.GetString("84", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ldap Timeout.
        /// </summary>
        public static string _85 {
            get {
                return ResourceManager.GetString("85", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Authentication Unknown.
        /// </summary>
        public static string _86 {
            get {
                return ResourceManager.GetString("86", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Filter Error.
        /// </summary>
        public static string _87 {
            get {
                return ResourceManager.GetString("87", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User Cancelled.
        /// </summary>
        public static string _88 {
            get {
                return ResourceManager.GetString("88", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parameter Error.
        /// </summary>
        public static string _89 {
            get {
                return ResourceManager.GetString("89", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Partial Results.
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No Memory.
        /// </summary>
        public static string _90 {
            get {
                return ResourceManager.GetString("90", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Connect Error.
        /// </summary>
        public static string _91 {
            get {
                return ResourceManager.GetString("91", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Ldap Not Supported.
        /// </summary>
        public static string _92 {
            get {
                return ResourceManager.GetString("92", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Control Not Found.
        /// </summary>
        public static string _93 {
            get {
                return ResourceManager.GetString("93", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No Results Returned.
        /// </summary>
        public static string _94 {
            get {
                return ResourceManager.GetString("94", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More Results To Return.
        /// </summary>
        public static string _95 {
            get {
                return ResourceManager.GetString("95", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Client Loop.
        /// </summary>
        public static string _96 {
            get {
                return ResourceManager.GetString("96", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Referral Limit Exceeded.
        /// </summary>
        public static string _97 {
            get {
                return ResourceManager.GetString("97", resourceCulture);
            }
        }
    }
}
